{
    "verifications": {
        "bin": {
            "address": null,
            "billPayEnabled": 0,
            "bin": "411111",
            "category": null,
            "city": null,
            "country": null,
            "debitOverCreditEnabled": 0,
            "locationType": null,
            "method": 2,
            "name": "HSBC BANK USA NATIONAL ASSOCIATION",
            "newBin": null,
            "numberLength": null,
            "phone": null,
            "pinlessSupport": null,
            "state": null,
            "transferEnabled": 0,
            "type": "credit",
            "website": null,
            "zip": null
        },
        "entity": {
            "address1": "121 ABC",
            "address2": null,
            "appleDomain": "api-test.payrix.com",
            "checkStage": "postboard",
            "city": "Aliso Viejo",
            "clientIp": null,
            "country": "USA",
            "created": "2021-10-07 11:51:41.5157",
            "creator": "t1_log_609d65d586a57e5361a9605",
            "currency": "USD",
            "custom": "",
            "customerPhone": "18788768765",
            "displayName": null,
            "ein": "111111111",
            "einType": "ssn",
            "email": "test@test.com",
            "fax": null,
            "firstDisbursement": null,
            "frozen": 0,
            "fullAddress": "121 ABC, ",
            "id": "t1_ent_615f178d7dd7be0a5baeb8e",
            "inactive": 0,
            "industry": null,
            "ipCreated": "172.69.34.237",
            "ipModified": "162.158.54.248",
            "irsFilingName": "Test Name",
            "locations": 1,
            "login": "t1_log_615f178d7cda5b3ff3ca106",
            "modified": "2022-11-17 09:22:56.303",
            "modifier": "t1_log_6305c596af10ee2d2dbc4d2",
            "name": "ApplePay",
            "parameter": "t1_prm_637643bf8d95b9d2695f9d9",
            "payoutSecondaryDescriptor": null,
            "phone": "1111111111",
            "public": 0,
            "refs": {
                "entity": "42119236490689220",
                "funding": "4445253535997",
                "member": "1",
                "merchant": "10647310954518616",
                "mid": "06678540"
            },
            "reserved": 0,
            "state": "CA",
            "tcAcceptDate": 201612111750,
            "tcAcceptIp": null,
            "tcDate": null,
            "tcIp": null,
            "tcVersion": null,
            "timezone": "pst",
            "tinStatus": 0,
            "totalCreditDisbursements": 0,
            "type": 2,
            "website": "http:\\/\\/Applepay.com",
            "zip": "92656"
        },
        "merchant": {
            "accountClosureReasonCode": null,
            "accountClosureReasonDate": null,
            "advancedBilling": 0,
            "amex": null,
            "amexVolume": 100000,
            "annualACHSaleVolume": null,
            "annualCCSaleVolume": null,
            "annualCCSales": 0,
            "applePayActive": 1,
            "applePayStatus": "approved",
            "autoBoarded": 1,
            "avgTicket": 0,
            "boarded": 20220328,
            "chargebackNotificationEmail": null,
            "chargebackRatio": null,
            "created": "2021-10-07 11:51:41.5581",
            "creator": "t1_log_609d65d586a57e5361a9605",
            "creditRatio": null,
            "creditTimeliness": null,
            "dba": "Apple Pay Test ",
            "disclosureDate": null,
            "disclosureIP": null,
            "discover": null,
            "entity": "t1_ent_615f178d7dd7be0a5baeb8e",
            "environment": "ecommerce",
            "established": 20211001,
            "expressBatchCloseMethod": null,
            "expressBatchCloseTime": null,
            "frozen": 0,
            "googlePayActive": 1,
            "id": "t1_mer_615f178d86f4634e392a915",
            "inactive": 0,
            "incrementalAuthSupported": 0,
            "lastActivity": "2023-02-06 08:42:15",
            "letterDate": null,
            "letterStatus": 0,
            "locationType": 77,
            "mcc": "0742",
            "modified": "2023-02-06 08:42:17.899",
            "modifier": "t1_log_63a49eceefb753fad65f0f5",
            "naics": null,
            "naicsDescription": null,
            "ndxDays": 2,
            "ndxPercentage": null,
            "new": 0,
            "omniTokenEnabled": null,
            "passTokenEnabled": null,
            "percentBusiness": 0,
            "percentEcomm": 100,
            "percentKeyed": 0,
            "qsa": null,
            "riskLevel": null,
            "saqDate": null,
            "saqType": null,
            "seasonal": 0,
            "status": 2,
            "statusReason": null,
            "tcAttestation": 0,
            "tcDate": null,
            "tcVersion": 0,
            "tinStatus": 0,
            "tmxSessionId": null,
            "totalApprovedSales": 6378966,
            "totalVolume": 1000000,
            "visaDisclosure": 0,
            "visaMvv": null
        },
        "ownership": {
            "division": null,
            "partition": "g157713aff9b946"
        },
        "payment": "g157b215cd94669",
        "restIds": " ",
        "transaction": {
            "address1": null,
            "address2": null,
            "allowPartial": 0,
            "approved": null,
            "authCode": null,
            "authDate": null,
            "authTokenCustomer": null,
            "authentication": null,
            "authenticationId": null,
            "authorization": null,
            "batch": null,
            "captured": null,
            "cashback": null,
            "channel": null,
            "checkStage": "auth",
            "city": null,
            "clientIp": "172.70.114.153",
            "cofType": null,
            "company": null,
            "convenienceFee": 0,
            "copyReason": null,
            "country": null,
            "created": "2023-03-31 11:56:53.8223",
            "creator": "t1_log_611e6ca320fae7afab2f256",
            "currency": "USD",
            "currencyConversion": null,
            "cvv": 1,
            "cvvStatus": null,
            "debtRepayment": "0",
            "description": null,
            "descriptor": "Apple Pay Test ",
            "discount": null,
            "duty": null,
            "email": null,
            "emv": 0,
            "entryMode": null,
            "expiration": "0823",
            "fbo": "WORLDPAY_FBO1",
            "fee": null,
            "feeConsumed": null,
            "first": "Fayssal",
            "fortxn": null,
            "fromtxn": null,
            "frozen": 0,
            "funded": null,
            "fundingCurrency": "USD",
            "fundingEnabled": "1",
            "id": "t1_txn_642702c5c8a9c02f7fd4d1f",
            "imported": 0,
            "inactive": 0,
            "ipCreated": "172.70.114.153",
            "ipModified": "172.70.114.153",
            "last": " Smawi",
            "merchant": "t1_mer_615f178d86f4634e392a915",
            "mid": "06678540",
            "middle": null,
            "misused": null,
            "mobile": null,
            "modified": "2023-03-31 11:56:53.8223",
            "modifier": "t1_log_611e6ca320fae7afab2f256",
            "order": "",
            "origin": "8",
            "originalApproved": null,
            "payment": "g157b215cd94669",
            "phone": null,
            "pin": 0,
            "pinEntryCapability": null,
            "platform": "VANTIV",
            "processedSequence": 0,
            "refunded": 0,
            "requestSequence": 0,
            "reserved": 0,
            "returned": null,
            "serviceCode": null,
            "settled": null,
            "settledCurrency": null,
            "settledTotal": null,
            "shipping": null,
            "signature": 0,
            "state": null,
            "statement": null,
            "status": 0,
            "subscription": null,
            "surcharge": null,
            "swiped": 0,
            "tax": null,
            "terminal": null,
            "terminalCapability": null,
            "token": null,
            "total": 100,
            "traceNumber": null,
            "type": "2",
            "unattended": null,
            "unauthReason": null,
            "zip": null
        },
        "txnRefs": {
            "threatMetrix": {
                "created": "2023-03-31 11:56:53.9681",
                "creator": "t1_log_611e6ca320fae7afab2f256",
                "id": "t1_trf_642702c5e9999a9c9888fd5",
                "modified": "2023-03-31 11:56:53.9681",
                "modifier": "t1_log_611e6ca320fae7afab2f256",
                "platform": "VANTIV",
                "ref": "ea701b69-c6f9-475e-8ce1-410f5df7cabb",
                "stage": "threatMetrix",
                "txn": "t1_txn_642702c5c8a9c02f7fd4d1f"
            }
        }
    }
}